import Head from 'next/head'
import Image from 'next/image'

import Navbar from './components/Navbar'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Stephen Talley</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/st4.svg" />
      </Head>

      <main className='main'>
        <Navbar></Navbar>
        <h1>Stephen Talley</h1>
        <p>Software Engineer</p>

  
      </main>

      <footer>
        <Image src="/st5.svg" alt="Vercel Logo" width={150} height={70} />
      </footer>
    </div>
  )
}
